### PR TITLE
Support CMPSB

### PR DESCRIPTION
**Pull request by tunz**
Support CMPSB

I targeted following scenario (toy4 strcmp)
```asm
  4011e4:       f3 a6                   repz cmpsb %es:(%rdi),%ds:(%rsi)
  4011e6:       0f 97 c2                seta   %dl
  4011e9:       0f 92 c0                setb   %al
  4011ec:       89 d1                   mov    %edx,%ecx
  4011ee:       28 c1                   sub    %al,%cl
  4011f0:       89 c8                   mov    %ecx,%eax
  4011f2:       0f be c0                movsbl %al,%eax
  4011f5:       85 c0                   test   %eax,%eax
  4011f7:       75 0c                   jne    401205 <main+0xa1>
  4011f9:       bf cb 65 49 00          mov    $0x4965cb,%edi
  4011fe:       e8 fd 0e 00 00          callq  402100 <_IO_puts>
```

```
$ python system.py --sym stdin examples/toy004-strcmp
...
...
...
Symbolic PC found, possible detinations are:  ['4011f9', '401205']
	Saving state state_00000000004011f9_6883.pkl
Program Finnished correctly
stdin:  '\x00\xc0\xf04X@\x804\n'
	 Loading state  state_00000000004011f9_6883.pkl
Program Finnished correctly
stdin:  'ZARAZA\x00A\n'
Results dumped in  ./pse_D8AtZZ
8733 2222.13740458
```

Please tell me if it does not work.

### CODE REVIEW

**Comment by feliam** [comment]
Woohoo! I'll check and merge this over the weekend.
Thanks thanks thanks!

**Comment by feliam** [comment]
There is a problem there.
You've put a *while* statement inside the definition of an instruction.
Each instruction handler may execute only one instruction. An loop by not advancing the PC.
Otherwise you'll nee to handle a symbolic count inside the inst handler.

**Comment by tunz** [comment]
I think we have to accumulate ZF and CF symbolic values.
We need to know whether it is the first time of executing the instruction or not to accumulate them.
Also, we don't need to break the loop, because we only need to know if the whole part is same or not.
So, I think _while_ statement is reasonable...

You mean the _count_ can be changed inside the _old\_method_?
So, we have to check the _count_ value inside the _while_ statement?
If so, I'll check and fix it.

**Comment by feliam** [comment]
I don't mean "count" changed inside old_method. I mean "count" being
symbolic as in read from user controllable environment (stdin).
Then if *count* is symbolic it is prefered that you don't do any "IF" or
"WHILE" on it. You may use it to construct other symb values like cpu.IF.

It should be like doing a "stepi" in gdb.

When count is symbolic you need to use the solver in order to make
decisions. You can't do "IF count" or "WHILE count>0". (or maybe using
object__nonzero__??)

**Pull request closed without merging**
